In [68]:
import numpy as np

In [69]:
# numpy stores data in consecutive location

In [70]:
# numpy is very fast


In [71]:
l = [1,2,3,4,]

In [72]:
a = np.array(l)

array([1, 2, 3, 4])

numpy.ndarray

In [74]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [75]:
d = [1,2,3,4,5 , "rg"]

In [77]:
np.array(d)

array(['1', '2', '3', '4', '5', 'rg'], dtype='<U11')

In [ ]:
# question mark trick

In [78]:
np.?

SyntaxError: invalid syntax (<ipython-input-78-a3a591b81872>, line 1)

In [79]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distance
    between two adjacent values, ``out[i+1]

In [80]:
a = np.arange(9)

In [81]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [83]:
b = np.arange(4,89)

In [84]:
b

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
       55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
       72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88])

In [85]:
# include the first element and exclude last

In [86]:
c = np.arange(5, 25,3)

In [87]:
c

array([ 5,  8, 11, 14, 17, 20, 23])

In [90]:
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [92]:
np.arange(100).reshape(5,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [93]:
c = np.array([[1,2,3,4] , [5,6,7,8]])

In [94]:
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [95]:
c = np.array([[1,2,3,4] , [5,6,7]])

In [96]:
c

array([list([1, 2, 3, 4]), list([5, 6, 7])], dtype=object)

In [97]:
### broadcasting

In [155]:
a=np.random.randint(1,10,(4,4))

In [156]:
a

array([[9, 1, 2, 7],
       [8, 1, 5, 1],
       [6, 2, 1, 8],
       [3, 8, 7, 2]])

In [157]:
b = np.random.randint(1,10,(2,2))

In [158]:
b

array([[5, 3],
       [7, 1]])

In [159]:
a+b

ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

In [160]:
# 1. shape should be same
# 2. rows are same and one of the column is one
# 3. columns are same and one of the row is one